### ISSUE TITLE
Error: key must be at least 16 characters long

### ISSUE THREAD

**Issue by ITR13** [getferdi/server-docker#10]
When following [this guide](https://github.com/getferdi/server-docker) on setting up a ferdi server with docker, accessing [domain]:3333 yields the following error:
```
Error: key must be at least 16 characters long
Error: key must be at least 16 characters long
    at module.exports (/app/node_modules/simple-encryptor/index.js:24:11)
    at new Encryption (/app/node_modules/@adonisjs/framework/src/Encryption/index.js:37:22)
    at Object.app.singleton [as closure] (/app/node_modules/@adonisjs/framework/providers/AppProvider.js:257:14)
    at Ioc._resolveBinding (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:231:68)
    at Ioc.make (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:807:19)
    at injections.map (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:318:19)
    at Array.map (<anonymous>)
    at Ioc._makeInstanceOf (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:317:44)
    at Ioc.make (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:799:19)
    at AuthManager.getScheme (/app/node_modules/@adonisjs/auth/src/Auth/Manager.js:86:16)
    at Auth.authenticator (/app/node_modules/@adonisjs/auth/src/Auth/index.js:118:40)
    at new Auth (/app/node_modules/@adonisjs/auth/src/Auth/index.js:68:39)
    at Context.<anonymous> (/app/node_modules/@adonisjs/auth/providers/AuthProvider.js:151:14)
    at Context.wrappedCallback [as auth] (/app/node_modules/macroable/index.js:132:61)
    at Server._handleException (/app/node_modules/@adonisjs/framework/src/Server/index.js:253:63)
    at _executeServerMiddleware.then.then.catch (/app/node_modules/@adonisjs/framework/src/Server/index.js:441:14)
```

To create the container I used the following command: (with MYDOMAIN replaced with my domain, and AREALLYLONGPASSWORD being a randomly generated password with over 20 characters)
```
sudo docker create \
    --name=ferdi-server \
    -e NODE_ENV=development \
    -e EXTERNAL_DOMAIN=MYDOMAIN \
    -e DB_CONNECTION=sqlite \
    -e DB_HOST=127.0.0.1 \
    -e DB_PORT=3306 \
    -e DB_USER=root \
    -e DB_PASSWORD=AREALLYLONGPASSWORD \
    -e DB_SSL=false \
    -e IS_CREATION_ENABLED=true \
    -e IS_DASHBOARD_ENABLED=true \
    -e IS_REGISTRATION_ENABLED=true \
    -e CONNECT_WITH_FRANZ=false \
    -p 3333:80 \
    -v ~/data/config:/config \
    -v ~/data/app/database:/app/database \
    -v ~/data/app/recipes:/app/recipes \
    --restart unless-stopped \
    getferdi/ferdi-server
```

It's running on `Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-51-generic x86_64)`

**Comment by xthursdayx** [comment]
I don't know what could be causing this issue. Can you try using an alpha-numeric password (no symbols) that is 16 characters long, just to see if that works. If so that will help us isolate what the problem is.

**Comment by ITR13** [comment]
Tried setting DB_PASSWORD to a 15, 16, and 17 long alphanumeric password to no avail. 

Could there be a separate variable needed for adonis? [This](https://forum.adonisjs.com/t/error-trying-to-make-login-test-key-must-be-at-least-16-characters/2932/2) search result mentions "APP_KEY", and I tried setting that to the same variable as DB_PASSWORD, and it now works. 

So I'm assuming whatever is supposed to set that isn't running properly.

**Comment by xthursdayx** [comment]
The `APP_KEY` variable is automatically generated by the image on first run by [this cont-init.d script](https://github.com/getferdi/server-docker/blob/master/root/etc/cont-init.d/50-config), which should then save you `APP_KEY` at `/config/FERDI_APP_KEY.txt`, so you shouldn't need to enter it manually. When you create and run this container for the first time do you see a `FERDI_APP_KEY.txt` being created in your config directory?

**Comment by wkelton** [comment]
It appears that the APP_KEY generation is failing on first run:
`ERROR  Cannot run key:generate command in production. Pass --force flag to continue`

**Comment by xthursdayx** [comment]
> It appears that the APP_KEY generation is failing on first run:
> `ERROR Cannot run key:generate command in production. Pass --force flag to continue`

Are you having this same problem? We haven't seen this issue with anyone other than @ITR13  yet, so if it's more widespread and an issue with the code then we'll certainly need to address it ASAP.

**Comment by waschinski** [comment]
> > It appears that the APP_KEY generation is failing on first run:
> > `ERROR Cannot run key:generate command in production. Pass --force flag to continue`
> 
> Are you having this same problem? We haven't seen this issue with anyone other than @ITR13 yet, so if it's more widespread and an issue with the code then we'll certainly need to address it ASAP.

I am getting the same along with a bunch of npm warnings as well as this thrice:
`.env: line 17: access: command not found`

Using postgres as database and `NODE_ENV` set to `production`.

**Comment by xthursdayx** [comment]
So, as it is currently deployed, the Ferdi server docker image is only tested to work with `NODE_ENV` set to `development`.  As @waschinski mentioned, `key:generate` is not able to run in production mode without the `--force` flag, which the current Docker image doesn't employ. 

There have been some major changes to Adonis since I originally built this image, so the entire image needs to be updated to reflect that since some of the components of Adonis in Ferdi-server are far out-of-date and prevent the server from being built in production mode (see https://github.com/getferdi/server/issues/45 and https://github.com/getferdi/server/pull/46). 

Much of the work to update this image has already been done by @k0staa and @cromefire and there are two existing PRs to update the image (https://github.com/getferdi/server-docker/pull/9) and merge the Docker image into the main Ferdi-server repo (https://github.com/getferdi/server/pull/48). However, these PRs will result in breaking changes for current Ferdi-server installations, and there are a couple of issues still need to be sorted out (e.g. implementing semver releases and updating the Docker build and publish process), so they have not been merged yet. 

For the moment, I would suggest running the docker image with `Node_ENV` set to `development` to see if that (temporarily) fixes the issue. 

Regarding the npm warnings, as mentioned here - https://github.com/getferdi/server-docker/issues/11 - they are related to out-of-date AdonisJS components in Ferdi-server itself, but hopefully these PRs will be cleared soon which should resolve the warnings.
